export type Direction = 'reference' | 'verse';
export type RecallMode = Direction | 'mixed';
export type TopicId = string;
export type Book = { id: string; name: string; order: number; testament: string; section: string; aliases: string[]; chapters: number; verseCount: number; chapterLengths: number[] };
export type Topic = { id: TopicId; name: string; group: string; icon: string; subtitle: string; aliases: string[]; counts: { curated: number; suggested: number } };
export type TopicAssignment = { topic: TopicId; basis: 'curated' | 'keyword'; sourceRange?: string };
export type Verse = {
  id: string;
  book: string;
  chapter: number;
  startVerse: number;
  endVerse: number;
  reference: string;
  text: string;
  translation: string;
  tags: TopicId[];
  sourceUrl: string;
  bookId?: string;
  testament?: string;
  section?: string;
  keywords?: string[];
  assignments?: TopicAssignment[];
  sourceIndex?: number;
  textNote?: string;
};
export type Progress = { box: number; due: string; reviews: number; lastReviewed: string };
export type Review = { id: string; verseId: string; direction: Direction; day: string; correct: boolean; newVerse: boolean };
export type Settings = { dailyGoal: number; newPerDay: number; mode: RecallMode; fontScale: number; reminderTime: string; reminderEnabled: boolean; celebrationsEnabled?: boolean };
export type VerseStack = { id: string; name: string; verseIds: string[]; updatedAt: string };
export type AppState = {
  lessons?: import('./lessons').Lesson[];
  stackDraft?: import('./lessons').StackDraft;
  version: 1;
  onboarded: boolean;
  settings: Settings;
  enrolled: string[];
  favorites: string[];
  progress: Record<string, Progress>;
  history: Review[];
  goalDays?: string[];
  stacks?: VerseStack[];
};
export type QueueItem = { verseId: string; direction: Direction; isNew: boolean };
